# Generated by Django 4.2.6 on 2023-10-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_image', '0002_hadiths_delete_imagewithtext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hadiths',
            new_name='hadithsModel',
        ),
    ]
