# Generated by Django 4.2.6 on 2023-10-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_image', '0004_hadithsmodel_chapter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tatorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
